//
// ********************************************************************
// * License and Disclaimer                                           *
// *                                                                  *
// * The  Geant4 software  is  copyright of the Copyright Holders  of *
// * the Geant4 Collaboration.  It is provided  under  the terms  and *
// * conditions of the Geant4 Software License,  included in the file *
// * LICENSE and available at  http://cern.ch/geant4/license .  These *
// * include a list of copyright holders.                             *
// *                                                                  *
// * Neither the authors of this software system, nor their employing *
// * institutes,nor the agencies providing financial support for this *
// * work  make  any representation or  warranty, express or implied, *
// * regarding  this  software system or assume any liability for its *
// * use.  Please see the license in the file  LICENSE  and URL above *
// * for the full disclaimer and the limitation of liability.         *
// *                                                                  *
// * This  code  implementation is the result of  the  scientific and *
// * technical work of the GEANT4 collaboration.                      *
// * By using,  copying,  modifying or  distributing the software (or *
// * any work based  on the software)  you  agree  to acknowledge its *
// * use  in  resulting  scientific  publications,  and indicate your *
// * acceptance of all terms of the Geant4 Software license.          *
// ********************************************************************
//
// \file   NEWDIR/include/TetModelImport.hh
// \generated by POLY2TET (author: Haegin Han)

#ifndef TetModelImport_h
#define TetModelImport_h 1

#include <stdlib.h>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <vector>
#include <map>

#include "G4UIExecutive.hh"
#include "G4SystemOfUnits.hh"
#include "G4PhysicalConstants.hh"
#include "G4ThreeVector.hh"
#include "G4String.hh"
#include "G4Tet.hh"
#include "G4NistManager.hh"
#include "G4Material.hh"
#include "G4Colour.hh"

class TetModelImport
{
public:
	TetModelImport(G4UIExecutive* ui);
	virtual ~TetModelImport() {};

	// get methods
	G4String      GetPhantomName()           { return phantomName; };
	G4Material*   GetMaterial(G4int idx)     { return materialMap[idx];}
	G4int         GetNumTetrahedron()        { return tetVector.size();}
	G4int         GetMaterialIndex(G4int idx){ return materialVector[idx]; }
	G4Tet*        GetTetrahedron(G4int idx)  { return tetVector[idx]; }
	G4double      GetVolume(G4int idx)       { return volumeMap[idx]; }
	std::map<G4int, G4double> GetMassMap()   { return massMap; }
	std::map<G4int, G4Colour> GetColourMap() { return colourMap; }
	G4ThreeVector GetPhantomSize()           { return phantomSize; }
	G4ThreeVector GetPhantomBoxMin()         { return boundingBox_Min; }
	G4ThreeVector GetPhantomBoxMax()         { return boundingBox_Max; }

private:
	void DataRead(G4String, G4String);
	void MaterialRead(G4String);
	void ColourRead();
	void PrintMaterialInfomation();

	G4String phantomDataPath;
	G4String phantomName;

	G4ThreeVector boundingBox_Min;
	G4ThreeVector boundingBox_Max;
	G4ThreeVector phantomSize;

	std::vector<G4ThreeVector> vertexVector;
	std::vector<G4Tet*>        tetVector;
	std::vector<G4int*>        eleVector;
	std::vector<G4int>         materialVector;
	std::map<G4int, G4int>     numTetMap;
	std::map<G4int, G4double>  volumeMap;
	std::map<G4int, G4double>  massMap;
	std::map<G4int, G4Colour>  colourMap;

	std::map<G4int, std::vector<std::pair<G4int, G4double>>> materialIndexMap;
	std::vector<G4int>                                       materialIndex;
	std::map<G4int, G4Material*>                             materialMap;
	std::map<G4int, G4double>                                densityMap;
	std::map<G4int, G4String>                                organNameMap;
};

#endif
