{PHANTOM} - Generated by POLY2TET
C ****************************************************************************
C                               CELL CARDS
C ****************************************************************************
C ----------------------------------------------------------------------------
C PSUEDO CELLS FOR ABAQUS
C ----------------------------------------------------------------------------
read file={PHANTOM}.cell
C ----------------------------------------------------------------------------
C LEGACY CELLS                                       
C ----------------------------------------------------------------------------
{c1}   0   -10  fill=2           $ Phantom box
{c2}   0   -99  10               $ Void in the world
{c3}   0        99               $ World

C ****************************************************************************
C                            SURFACE CARDS
C ****************************************************************************
10  rpp -{HX} {HX} -{HY} {HY} -{HZ} {HZ}   $ Phantom box
99  box -1000 -1000 -1000 2000 0 0 0 2000 0 0 0 2000   $ World boundary

C ****************************************************************************
C                               DATA CARDS
C ****************************************************************************
dbcn 48j 1                     $ Debug information             
mode p e                       $ Track photons and electrons    
mphys on                       $ Turn on model physics         
imp:p,e 1 {impNo}r 0               $ Importance                    
prdmp 10000000 10000000  -1    $ Print and dump cycle          
rand  seed=RNSEED              $ Random seed                   
nps 1000000                   $ Number of particles           
sdef par=p erg=1.00 x=d1  y=-50 z=d2 vec=0 1 0 dir=1 
SI1 -{HX} {HX}
SP1 0 1
SI2 -{HZ} {HZ}
SP2 0 1                         $ General source definition     
C ----------------------------------------------------------------------------
C TALLIES FOR EACH ORGAN/TISSUE
C ----------------------------------------------------------------------------
read file={PHANTOM}.tally
C ----------------------------------------------------------------------------
C MATERIAL DATA FOR EACH ORGAN/TISSUE
C ----------------------------------------------------------------------------
read file={PHANTOM}.material
C ----------------------------------------------------------------------------
C EMBED is required for embedding a mesh geometry into MCNP6 input
embed2 meshgeo=abaqus                      $ Format specification  
       mgeoin={PHANTOM}.inp
       background=99999                    $ Cell number of the background
